// Function to update the display of continents covered
function updateContinentsCovered() {

    const countryToContinent = {
        "AF": "Africa", 
        "AL": "Europe", 
        "DZ": "Africa", 
        "AI": "North America", 
        "AM": "Asia", 
        "AW": "North America", 
        "AT": "Europe", 
        "BH": "Asia", 
        "BD": "Asia", 
        "BB": "North America", 
        "BY": "Europe", 
        "BE": "Europe", 
        "BZ": "North America", 
        "BJ": "Africa", 
        "BM": "North America", 
        "BT": "Asia", 
        "BO": "South America", 
        "BA": "Europe", 
        "BW": "Africa", 
        "BR": "South America", 
        "VG": "North America", 
        "BN": "Asia", 
        "BG": "Europe", 
        "BF": "Africa", 
        "BI": "Africa", 
        "KH": "Asia", 
        "CM": "Africa", 
        "CF": "Africa", 
        "TD": "Africa", 
        "CO": "South America", 
        "CR": "North America", 
        "HR": "Europe", 
        "CU": "North America", 
        "CW": "North America", 
        "CZ": "Europe", 
        "CI": "Africa", 
        "KP": "Asia", 
        "CD": "Africa", 
        "DJ": "Africa", 
        "DM": "North America", 
        "DO": "North America", 
        "EC": "South America", 
        "EG": "Africa", 
        "SV": "North America", 
        "GQ": "Africa", 
        "ER": "Africa", 
        "EE": "Europe", 
        "ET": "Africa", 
        "FI": "Europe", 
        "GF": "South America", 
        "GA": "Africa", 
        "GE": "Asia", 
        "DE": "Europe", 
        "GH": "Africa", 
        "GL": "North America", 
        "GD": "North America", 
        "GU": "North America", 
        "GT": "North America", 
        "GN": "Africa", 
        "GW": "Africa", 
        "GY": "South America", 
        "HT": "North America", 
        "HN": "North America", 
        "HU": "Europe", 
        "IS": "Europe", 
        "IN": "Asia", 
        "IR": "Asia", 
        "IQ": "Asia", 
        "IE": "Europe", 
        "IL": "Asia", 
        "JM": "North America", 
        "JO": "Asia", 
        "KZ": "Asia", 
        "KE": "Africa", 
        "XK": "Europe", 
        "KW": "Asia", 
        "KG": "Asia", 
        "LA": "Asia", 
        "LV": "Europe", 
        "LB": "Asia", 
        "LS": "Africa", 
        "LR": "Africa", 
        "LY": "Africa", 
        "LT": "Europe", 
        "LU": "Europe", 
        "MK": "Europe", 
        "MG": "Africa", 
        "MW": "Africa", 
        "MV": "Asia", 
        "ML": "Africa", 
        "MH": "Oceania", 
        "MQ": "North America", 
        "MR": "Africa", 
        "YT": "Africa", 
        "MX": "North America", 
        "MD": "Europe", 
        "MN": "Asia", 
        "ME": "Europe", 
        "MS": "North America", 
        "MA": "Africa", 
        "MZ": "Africa", 
        "MM": "Asia", 
        "NA": "Africa", 
        "NR": "Oceania", 
        "NP": "Asia", 
        "NL": "Europe", 
        "BQBO": "North America", 
        "NI": "North America", 
        "NE": "Africa", 
        "NG": "Africa", 
        "PK": "Asia", 
        "PW": "Oceania", 
        "PS": "Asia", 
        "PA": "North America", 
        "PY": "South America", 
        "PE": "South America", 
        "PL": "Europe", 
        "PT": "Europe", 
        "QA": "Asia", 
        "CG": "Africa", 
        "KR": "Asia", 
        "RE": "Africa", 
        "RO": "Europe", 
        "RW": "Africa", 
        "BQSA": "North America", 
        "LC": "North America", 
        "VC": "North America", 
        "BL": "North America", 
        "MF": "North America", 
        "SA": "Asia", 
        "SN": "Africa", 
        "RS": "Europe", 
        "SL": "Africa", 
        "SX": "North America", 
        "SK": "Europe", 
        "SI": "Europe", 
        "SO": "Africa", 
        "ZA": "Africa", 
        "SS": "Africa", 
        "ES": "Europe", 
        "LK": "Asia", 
        "BQSE": "North America", 
        "SD": "Africa", 
        "SR": "South America", 
        "SZ": "Africa", 
        "SE": "Europe", 
        "CH": "Europe", 
        "SY": "Asia", 
        "TW": "Asia", 
        "TJ": "Asia", 
        "TZ": "Africa", 
        "TH": "Asia", 
        "GM": "Africa", 
        "TL": "Asia", 
        "TG": "Africa", 
        "TN": "Africa", 
        "TM": "Asia", 
        "TV": "Oceania", 
        "UG": "Africa", 
        "UA": "Europe", 
        "AE": "Asia", 
        "UY": "South America", 
        "UZ": "Asia", 
        "VE": "South America", 
        "VN": "Asia", 
        "EH": "Africa", 
        "YE": "Asia", 
        "ZM": "Africa", 
        "ZW": "Africa"
    };
    
    const visitedContinents = new Set();

    // Iterate through visited countries
    userData.countriesVisited.forEach(code => {
        const continent = countryToContinent[code.toUpperCase()];
        console.log(continent)
        if (continent) {
            visitedContinents.add(continent);
        }
    });
    console.log(visitedContinents.size)

    // Return the number of unique continents visited
    return visitedContinents.size;

}

updateContinentsCovered()

